# Generated by Django 5.1.5 on 2025-02-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='guest_2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
