name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"  # Use a stable version

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          poetry install --no-root  # Install only the dependencies (not the package)

      - name: Run Ruff Linter
        run: |
          poetry run ruff check .  # Run Ruff on the entire codebase

  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-13-60-171-240.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@ec2-13-60-171-240.eu-north-1.compute.amazonaws.com << 'EOF'
            cd /var/www/djangor-backend
            source .venv/bin/activate
            git pull origin main
            poetry install --only main --no-root
            python3 backend/manage.py migrate
            python3 backend/manage.py collectstatic --noinput
            sudo systemctl restart uwsgi
          EOF
